name: Test Functions

on:
  pull_request:
    paths:
      - "functions/**"
  push:
    branches:
      - main
    paths:
      - "functions/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
      
      - name: "Set up Python"
        run: |
          cd functions
          uv python install
          

      - name: Install the project
        run: | 
          cd functions
          uv sync --all-extras --dev

      - name: Run unit tests with coverage
        run: |
          cd functions
          uv run pytest --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}